### ISSUE TITLE
Payment test data

### ISSUE THREAD

**Issue by Tobi406** [jmprathab/MyHome#255] opened 2021-03-07 18:23 UTC
## The problem
Currently default test data for payments is being missed. This hinders the development flow, when you have to add data after every restart. It would be nice if such data could be added.

**Comment by suraj4652** [comment] 2021-04-19 14:48
Can I take up this task.

**Comment by suraj4652** [comment] 2021-04-19 17:05
In Payment.java bean, below 2 attribute should have OneToOne Mapping. 

private User admin;
private HouseMember member;

**Comment by trangntt-016** [comment] 2021-08-05 22:02
Can I pick up this task?

**Comment by kajalrawal** [comment] 2021-09-27 16:08
@Tobi406 Please assign this issue to me, I would like to fix it

**Comment by jucron** [comment] 2022-02-23 11:34
Hello! I would like to contribute to this issue. Thank you

**Comment by sann3** [comment] 2022-10-07 15:11
Seems the issue is fixed, can you please close the issue.

**Closed as completed** 2022-10-07 19:27 UTC
Labels: enhancement, good first issue, up-for-grabs
